version: '3.8'
services:
  db:
    image: postgres:15.2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:create db:setup && bundle exec rake db:create db:setup RAILS_ENV=test && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mighty
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
volumes:
  postgres: